[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
miniserve = { path = "../miniserve" }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
tokio = { version = "1", features = ["full"] }
